package transportesramloy;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author MKP
 */
public class ProductosDialog extends javax.swing.JDialog {

    protected static int producto_id;

    /**
     * Creates new form ProductosDialog
     *
     * @param parent
     * @param modal
     */
    public ProductosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon1 = new ImageIcon(getClass().getResource("icons/Product_20px.png"));
        setIconImage(icon1.getImage());
        Otros ver = new Otros();
        ver.ProductosVer(producto_id);
        setLocationRelativeTo(menu.panelPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prod_id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prod_nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        check_activo = new javax.swing.JCheckBox();
        check_inactivo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ImageIcon icon = new ImageIcon(this.getClass().getResource("fondos/" + TransportesRamloy.miFondo));
        Image img = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paintComponent(g);
            }
        };

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(131, 2, 7));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Product_60px.png"))); // NOI18N
        jLabel1.setText("PRODUCTO NO.");

        prod_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prod_id.setForeground(new java.awt.Color(131, 2, 7));
        prod_id.setText("#");

        jLabel3.setText("NOMBRE:");

        prod_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prod_nomKeyTyped(evt);
            }
        });

        jLabel4.setText("ESTATUS");

        check_activo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_activo.setText("ACTIVO");
        check_activo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_activoItemStateChanged(evt);
            }
        });

        check_inactivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_inactivo.setText("INACTIVO");
        check_inactivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_inactivoItemStateChanged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Delete_20px.png"))); // NOI18N
        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Save_20px.png"))); // NOI18N
        jButton2.setText("GUARDAR CAMBIOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(check_activo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(check_inactivo))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prod_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(prod_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(prod_id)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prod_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_activo)
                            .addComponent(check_inactivo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_activoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_activoItemStateChanged
        if (check_activo.isSelected()) {
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
        } else {
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
        }
    }//GEN-LAST:event_check_activoItemStateChanged

    private void check_inactivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_inactivoItemStateChanged
        if (check_inactivo.isSelected()) {
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
        } else {
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
        }
    }//GEN-LAST:event_check_inactivoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (prod_nom.getText().length() == 0) {
            Alerts alerta = new Alerts();
            alerta.alertWarning("EL NOMBRE DEL PRODUCTO ES NECESARIO.", "ERROR");
        } else {
            Icon icono2 = new ImageIcon(getClass().getResource("icons/Help_48px.png"));
            int opcion = JOptionPane.showConfirmDialog(null, "¿DESEAS GUARDAR LOS DATOS?", "AVISO", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2);
            if (opcion == 0) {
                String nombre;
                String status;
                nombre = prod_nom.getText();
                if (check_activo.isSelected()) {
                    status = "ACTIVO";
                } else {
                    status = "INACTIVO";
                }
                Otros update = new Otros();
                update.ProductosActualizar(producto_id, nombre, status);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Icon icono2 = new ImageIcon(getClass().getResource("icons/error_48.png"));
        int opcion = JOptionPane.showConfirmDialog(null, "¿DESEAS ELIMINAR EL PRODUCTO NO. " + producto_id + "?", "AVISO", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2);
        if (opcion == 0) {
            Otros delete = new Otros();
            delete.ProductosEliminar(producto_id);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prod_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_nomKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (prod_nom.getText().length() >= 200) {
            evt.consume();
            prod_nom.setForeground(Color.red);
        } else {
            prod_nom.setForeground(Color.black);
        }
    }//GEN-LAST:event_prod_nomKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JCheckBox check_activo;
    protected static javax.swing.JCheckBox check_inactivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JLabel prod_id;
    protected static javax.swing.JTextField prod_nom;
    // End of variables declaration//GEN-END:variables
}
