package transportesramloy;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.Image;
import java.awt.Graphics;

/**
 *
 * @author Ing. Felipe Omar Ramos C. Desarrollador Mikrobyte Puebla S.A. de C.V.
 */
public class ProveedorDialog extends javax.swing.JDialog {

    protected static int proveedor_id;

    /**
     * Creates new form ProveedorDialog
     *
     * @param parent
     * @param modal
     */
    public ProveedorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon1 = new ImageIcon(getClass().getResource("icons/Proveedores_20px.png"));
        setIconImage(icon1.getImage());
        Proveedor ver = new Proveedor();
        ver.Ver(proveedor_id);
        setLocationRelativeTo(menu.panelPrincipal);
    }

    protected void limit(int limite, JTextField caja, KeyEvent evt) {
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }

        if (caja.getText().length() >= limite) {
            evt.consume();
            caja.setForeground(Color.red);
        } else {
            caja.setForeground(Color.black);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prov_id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prov_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prov_rfc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prov_calle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prov_colonia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prov_pobla = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        prov_estado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        prov_cp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prov_tel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        check_activo = new javax.swing.JCheckBox();
        check_inactivo = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ImageIcon icon = new ImageIcon(this.getClass().getResource("fondos/" + TransportesRamloy.miFondo));
        Image img = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paintComponent(g);
            }
        };

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Proveedores_60px.png"))); // NOI18N
        jLabel1.setText("PROVEEDOR NO.");

        prov_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prov_id.setText("#");

        jLabel3.setText("NOMBRE:");

        prov_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_nombreKeyTyped(evt);
            }
        });

        jLabel4.setText("RFC:");

        prov_rfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_rfcKeyTyped(evt);
            }
        });

        jLabel5.setText("CALLE:");

        prov_calle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_calleKeyTyped(evt);
            }
        });

        jLabel6.setText("COLONIA:");

        prov_colonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_coloniaKeyTyped(evt);
            }
        });

        jLabel7.setText("POBLACIÓN:");

        prov_pobla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_poblaKeyTyped(evt);
            }
        });

        jLabel8.setText("ESTADO:");

        prov_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_estadoKeyTyped(evt);
            }
        });

        jLabel9.setText("CP:");

        prov_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_cpKeyTyped(evt);
            }
        });

        jLabel10.setText("TELÉFONO:");

        prov_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov_telKeyTyped(evt);
            }
        });

        jLabel11.setText("ESTATUS:");

        check_activo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_activo.setText("ACTIVO");
        check_activo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_activoItemStateChanged(evt);
            }
        });

        check_inactivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_inactivo.setText("INACTIVO");
        check_inactivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_inactivoItemStateChanged(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Save_20px.png"))); // NOI18N
        jButton2.setText("GUARDAR CAMBIOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(prov_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prov_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(prov_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prov_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prov_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(prov_pobla, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(245, 245, 245))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(prov_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(prov_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prov_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(check_activo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_inactivo)
                        .addGap(189, 189, 189)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prov_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prov_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prov_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prov_pobla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prov_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_activo)
                    .addComponent(check_inactivo)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_activoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_activoItemStateChanged
        if (check_activo.isSelected()) {
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
        } else {
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
        }
    }//GEN-LAST:event_check_activoItemStateChanged

    private void check_inactivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_inactivoItemStateChanged
        if (check_inactivo.isSelected()) {
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
        } else {
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
        }
    }//GEN-LAST:event_check_inactivoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (prov_nombre.getText().length() == 0) {
            Alerts alerta = new Alerts();
            alerta.alertWarning("EL NOMBRE DEL PROVEEDOR ES NECESARIO.", "ERROR");
        } else {
            Icon icono2 = new ImageIcon(getClass().getResource("icons/Help_48px.png"));
            int opcion = JOptionPane.showConfirmDialog(null, "¿DESEAS GUARDAR LOS DATOS?", "AVISO", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2);
            if (opcion == 0) {
                String[] datos = new String[9];
                datos[0] = prov_nombre.getText();
                datos[1] = prov_calle.getText();
                datos[2] = prov_colonia.getText();
                datos[3] = prov_pobla.getText();
                datos[4] = prov_estado.getText();
                datos[5] = prov_tel.getText();
                datos[6] = prov_rfc.getText();
                datos[7] = prov_cp.getText();
                if (check_activo.isSelected()) {
                    datos[8] = "ACTIVO";
                } else {
                    datos[8] = "INACTIVO";
                }
                Proveedor update = new Proveedor();
                update.Actualizar(proveedor_id, datos);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void prov_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_nombreKeyTyped
        limit(150, prov_nombre, evt);
    }//GEN-LAST:event_prov_nombreKeyTyped

    private void prov_rfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_rfcKeyTyped
        limit(20, prov_rfc, evt);
    }//GEN-LAST:event_prov_rfcKeyTyped

    private void prov_calleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_calleKeyTyped
        limit(100, prov_calle, evt);
    }//GEN-LAST:event_prov_calleKeyTyped

    private void prov_coloniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_coloniaKeyTyped
        limit(100, prov_colonia, evt);
    }//GEN-LAST:event_prov_coloniaKeyTyped

    private void prov_poblaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_poblaKeyTyped
        limit(50, prov_pobla, evt);
    }//GEN-LAST:event_prov_poblaKeyTyped

    private void prov_estadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_estadoKeyTyped
        limit(30, prov_estado, evt);
    }//GEN-LAST:event_prov_estadoKeyTyped

    private void prov_cpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_cpKeyTyped
        limit(5, prov_cp, evt);
    }//GEN-LAST:event_prov_cpKeyTyped

    private void prov_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov_telKeyTyped
        limit(30, prov_tel, evt);
    }//GEN-LAST:event_prov_telKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JCheckBox check_activo;
    protected static javax.swing.JCheckBox check_inactivo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JTextField prov_calle;
    protected static javax.swing.JTextField prov_colonia;
    protected static javax.swing.JTextField prov_cp;
    protected static javax.swing.JTextField prov_estado;
    protected static javax.swing.JLabel prov_id;
    protected static javax.swing.JTextField prov_nombre;
    protected static javax.swing.JTextField prov_pobla;
    protected static javax.swing.JTextField prov_rfc;
    protected static javax.swing.JTextField prov_tel;
    // End of variables declaration//GEN-END:variables
}
