package transportesramloy;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.Image;
import java.awt.Graphics;

/**
 *
 * @author Ing. Felipe Omar Ramos C. Desarrollador Mikrobyte Puebla S.A. de C.V.
 */
public class UnidadDialog extends javax.swing.JDialog {

    protected static int unidad_id;

    /**
     * Creates new form UnidadDialog
     *
     * @param parent
     * @param modal
     */
    public UnidadDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon1 = new ImageIcon(getClass().getResource("icons/Driver_20px.png"));
        setIconImage(icon1.getImage());
        Unidad ver = new Unidad();
        ver.Ver(unidad_id);
        setLocationRelativeTo(menu.panelPrincipal);
    }

    protected void limit(int limite, JTextField caja, KeyEvent evt) {
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }

        if (caja.getText().length() >= limite) {
            evt.consume();
            caja.setForeground(Color.red);
        } else {
            caja.setForeground(Color.black);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uni_id = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uni_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        uni_dir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uni_tel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uni_unidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uni_placa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        check_activo = new javax.swing.JCheckBox();
        check_inactivo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        ImageIcon icon = new ImageIcon(this.getClass().getResource("fondos/" + TransportesRamloy.miFondo));
        Image img = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paintComponent(g);
            }
        };

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Driver_60px.png"))); // NOI18N
        jLabel4.setText("OPERADOR NO");

        uni_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uni_id.setText("#");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Delete_20px.png"))); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("NOMBRE:");

        uni_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uni_nombreKeyTyped(evt);
            }
        });

        jLabel1.setText("DIRECCIÓN:");

        uni_dir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uni_dirKeyTyped(evt);
            }
        });

        jLabel5.setText("TELÉFONO:");

        uni_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uni_telKeyTyped(evt);
            }
        });

        jLabel6.setText("UNIDAD:");

        uni_unidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uni_unidadKeyTyped(evt);
            }
        });

        jLabel7.setText("PLACA:");

        uni_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uni_placaKeyTyped(evt);
            }
        });

        jLabel8.setText("ESTATUS:");

        check_activo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_activo.setText("ACTIVO");
        check_activo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_activoItemStateChanged(evt);
            }
        });

        check_inactivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_inactivo.setText("INACTIVO");
        check_inactivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check_inactivoItemStateChanged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transportesramloy/icons/Save_20px.png"))); // NOI18N
        jButton1.setText("GUARDAR CAMBIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(check_activo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(check_inactivo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uni_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(uni_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(uni_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(uni_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(uni_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(uni_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(uni_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uni_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uni_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uni_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_activo)
                            .addComponent(check_inactivo)))
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_activoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_activoItemStateChanged
        if (check_activo.isSelected()) {
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
        } else {
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
        }
    }//GEN-LAST:event_check_activoItemStateChanged

    private void check_inactivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check_inactivoItemStateChanged
        if (check_inactivo.isSelected()) {
            check_inactivo.setSelected(true);
            check_inactivo.setForeground(Color.decode("#DD4B39"));
            check_activo.setSelected(false);
            check_activo.setForeground(Color.black);
        } else {
            check_inactivo.setSelected(false);
            check_inactivo.setForeground(Color.black);
            check_activo.setSelected(true);
            check_activo.setForeground(Color.decode("#00A65A"));
        }
    }//GEN-LAST:event_check_inactivoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (uni_nombre.getText().length() == 0) {
            Alerts alerta = new Alerts();
            alerta.alertWarning("EL NOMBRE DEL OPERADOR ES NECESARIO.", "ERROR");
        } else {
            Icon icono2 = new ImageIcon(getClass().getResource("icons/Help_48px.png"));
            int opcion = JOptionPane.showConfirmDialog(null, "¿DESEAS GUARDAR LOS DATOS?", "AVISO", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2);
            if (opcion == 0) {
                String[] datos = new String[6];
                datos[0] = uni_nombre.getText();
                datos[1] = uni_dir.getText();
                datos[2] = uni_tel.getText();
                datos[3] = uni_unidad.getText();
                datos[4] = uni_placa.getText();
                if (check_activo.isSelected()) {
                    datos[5] = "ACTIVO";
                } else {
                    datos[5] = "INACTIVO";
                }
                Unidad update = new Unidad();
                update.Actualizar(unidad_id, datos);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Icon icono2 = new ImageIcon(getClass().getResource("icons/error_48.png"));
        int opcion = JOptionPane.showConfirmDialog(null, "¿DESEAS ELIMINAR EL OPERADOR NO. " + unidad_id + "?", "AVISO", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2);
        if (opcion == 0) {
            Unidad delete = new Unidad();
            delete.Eliminar(unidad_id);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uni_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uni_nombreKeyTyped
        limit(150, uni_nombre, evt);
    }//GEN-LAST:event_uni_nombreKeyTyped

    private void uni_dirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uni_dirKeyTyped
        limit(150, uni_dir, evt);
    }//GEN-LAST:event_uni_dirKeyTyped

    private void uni_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uni_telKeyTyped
        limit(30, uni_tel, evt);
    }//GEN-LAST:event_uni_telKeyTyped

    private void uni_unidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uni_unidadKeyTyped
        limit(15, uni_unidad, evt);
    }//GEN-LAST:event_uni_unidadKeyTyped

    private void uni_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uni_placaKeyTyped
        limit(15, uni_placa, evt);
    }//GEN-LAST:event_uni_placaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JCheckBox check_activo;
    protected static javax.swing.JCheckBox check_inactivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JTextField uni_dir;
    protected static javax.swing.JLabel uni_id;
    protected static javax.swing.JTextField uni_nombre;
    protected static javax.swing.JTextField uni_placa;
    protected static javax.swing.JTextField uni_tel;
    protected static javax.swing.JTextField uni_unidad;
    // End of variables declaration//GEN-END:variables
}
